import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import { clsx } from "clsx";
const inter = Inter({ subsets: ["latin"] });
import { Analytics } from "@vercel/analytics/react";
export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={clsx(inter.className, "bg-neutral-50")}>
        {children}
        <footer className="px-8 py-16 bg-white">
          <div className="max-w-screen-md mx-auto">
            <p className="mb-4">
              <span className="text-2xl">🍱</span>
              <span className="text-xl font-semibold"> Bentisca</span>
            </p>
            <p>
              Created by{" "}
              <a
                href="https://github.com/JulianKominovic"
                target="_blank"
                rel="noopener noreferrer"
                className="underline underline-offset-2"
              >
                Julian Kominovic
              </a>{" "}
              using{" "}
              <a
                href="https://www.figma.com/community/file/1232620929235403629"
                target="_blank"
                rel="noopener noreferrer"
                className="underline underline-offset-2"
              >
                {"Double Glitch's Figma design"}
              </a>{" "}
              and{" "}
              <a
                href="https://simpleicons.org/"
                target="_blank"
                rel="noopener noreferrer"
              >
                SimpleIcons library
              </a>
            </p>
          </div>
        </footer>
        <Analytics />
      </body>
    </html>
  );
}
